language: node_js
node_js: '8'
cache: yarn
env:
  global:
    secure: bMp7fMvCUigUfmv3Ha5lEab+XaJ9x+4uzqD6Xt3+jF6Zhk47b9QX5y5p8pPGZ1I/ngHAaGFBmbTUMRSF3QmQYafOUIBUJnAPCL2QeMhdjimagyShq3qTanKnC3RMrZqG8uH+rACA4lvI5md1QLkVVPAW61n9+lb+pk+fk84HZTslSayMDpP119lao4F/9Yf74QsWxGgDKSeqSJfY/moReuK0VYKLAZlngJJtT6N7NYkcMgAmGS3Eq5xaCPWn0Rmi2aSpFfewT2iJj57CHsGGVvsEfSW7tL1MWwBWVkm8zYTR6Amv6h+xDa2gJlrcU1gWCs6HpTfB7WxKoJYxyW5y/C+yfQ2inps5jiXpn8GVD5DDT2gmdgaFYlhrv9tQr4pXtPe3Tg2s9kouOakshktukTr6P4hN0Am/R9mLkbqrLY5hR4pPGIN1UgrE0e3wlizu5aktQNdgTlw9FSyY66RFOzerRuZ3R6h0EbAQF7khZvyD3QK8/QBHeUXcHwV9ZiZNap+pxg6//LJugUoTEa0aR96oakFx/Md4vLpV7FCoLRSqmaChcxy+lINV0CZJHuDis3f4RRz5WnKlDRswuLkwxtuB4f1lnLNm27dkGnr1tYplyl/C0Z2Fq/gyh+w4xEoeKFb5e/JVgX2NKrY+lB8lc9oRDaYareKUWk6GDy6+gFQ=
